// Interface automatically generated by schemas-to-ts

import { BannerSlideComponent } from '../../components/interfaces/BannerSlideComponent';
import { BannerSlideComponent_Plain } from '../../components/interfaces/BannerSlideComponent';
import { BannerSlideComponent_NoRelations } from '../../components/interfaces/BannerSlideComponent';

export interface BannerComponent {
  slides: BannerSlideComponent[];
}
export interface BannerComponent_Plain {
  slides: BannerSlideComponent_Plain[];
}

export interface BannerComponent_NoRelations {
  slides: BannerSlideComponent_NoRelations[];
}

