// Interface automatically generated by schemas-to-ts

import { BannerSlide } from '../../components/interfaces/BannerSlide';
import { BannerSlide_Plain } from '../../components/interfaces/BannerSlide';
import { BannerSlide_NoRelations } from '../../components/interfaces/BannerSlide';

export interface Banner {
  slides: BannerSlide[];
}
export interface Banner_Plain {
  slides: BannerSlide_Plain[];
}

export interface Banner_NoRelations {
  slides: BannerSlide_NoRelations[];
}

