// Interface automatically generated by schemas-to-ts

export interface PageStandart {
  slug: string;
}

export interface PageStandart_Plain {
  slug: string;
}

export interface PageStandart_NoRelations {
  slug: string;
}
