// Interface automatically generated by schemas-to-ts

export interface PageBlogComponent {
  slug: string;
}
export interface PageBlogComponent_Plain {
  slug: string;
}

export interface PageBlogComponent_NoRelations {
  slug: string;
}

