// Interface automatically generated by schemas-to-ts

export interface PageStandartComponent {
  slug?: string;
}
export interface PageStandartComponent_Plain {
  slug?: string;
}

export interface PageStandartComponent_NoRelations {
  slug?: string;
}

