// Interface automatically generated by schemas-to-ts

export interface PageBlog {
  slug: string;
}

export interface PageBlog_Plain {
  slug: string;
}

export interface PageBlog_NoRelations {
  slug: string;
}
