// Interface automatically generated by schemas-to-ts

export interface Button {
  text: string;
}
export interface Button_Plain {
  text: string;
}

export interface Button_NoRelations {
  text: string;
}

