// Interface automatically generated by schemas-to-ts

export interface ButtonComponent {
  text: string;
}

export interface ButtonComponent_Plain {
  text: string;
}

export interface ButtonComponent_NoRelations {
  text: string;
}
