// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export enum SocialNetworkEnum {
  Facebook = 'Facebook',
  Twitter = 'Twitter',}

export interface MetaSocialComponent {
  socialNetwork: SocialNetworkEnum;
  title: string;
  description: string;
  image?: { data: Media };
}
export interface MetaSocialComponent_Plain {
  socialNetwork: SocialNetworkEnum;
  title: string;
  description: string;
  image?: Media;
}

export interface MetaSocialComponent_NoRelations {
  socialNetwork: SocialNetworkEnum;
  title: string;
  description: string;
  image?: number;
}

