// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { MetaSocialComponent } from './MetaSocialComponent';
import { MetaSocialComponent_Plain } from './MetaSocialComponent';
import { MetaSocialComponent_NoRelations } from './MetaSocialComponent';

export interface SeoComponent {
  metaTitle: string;
  metaDescription: string;
  metaImage?: { data: Media };
  metaSocial: MetaSocialComponent[];
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}
export interface SeoComponent_Plain {
  metaTitle: string;
  metaDescription: string;
  metaImage?: Media;
  metaSocial: MetaSocialComponent_Plain[];
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}

export interface SeoComponent_NoRelations {
  metaTitle: string;
  metaDescription: string;
  metaImage?: number;
  metaSocial: MetaSocialComponent_NoRelations[];
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}

