import type {ReactNode} from "react";
import type {Metadata} from "next";
import type {Locale} from "@/lib/i18n/locales"
import "./globals.css";
import {Header} from "@/components/layout/header";
import {DraftModeWidget} from "@/components/layout/draft-mode";

// todo implement strapi hooks to revalidate data
export const revalidate = 3600

export type LocaleParams = {
    params: {
        locale: Locale
    }
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children, params
                                   }: Readonly<{
    children: ReactNode;
}> & LocaleParams) {
    return (
        <html lang={params.locale}>
        <body className={`antialiased`}>
        <Header locale={params.locale}/>
        {children}

        <DraftModeWidget/>
        </body>
        </html>
    );
}
