// Interface automatically generated by schemas-to-ts

export interface Localization {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    main: any;
    locale: string;
    localizations?: { data: Localization[] };
  };
}
export interface Localization_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  main: any;
  locale: string;
  localizations?: Localization[];
}

export interface Localization_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  main: any;
  locale: string;
  localizations?: Localization[];
}

export interface Localization_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  main: any;
  locale: string;
  localizations?: Localization[];
}
