// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Button } from '../../shared/interfaces/Button';
import { Button_Plain } from '../../shared/interfaces/Button';
import { Button_NoRelations } from '../../shared/interfaces/Button';

export interface BannerSlide {
  image: { data: Media };
  title?: string;
  description?: string;
  buttons: Button[];
}
export interface BannerSlide_Plain {
  image: Media;
  title?: string;
  description?: string;
  buttons: Button_Plain[];
}

export interface BannerSlide_NoRelations {
  image: number;
  title?: string;
  description?: string;
  buttons: Button_NoRelations[];
}

