// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { ButtonComponent } from './ButtonComponent';
import { ButtonComponent_Plain } from './ButtonComponent';
import { ButtonComponent_NoRelations } from './ButtonComponent';

export interface BannerSlideComponent {
  image: { data: Media };
  title?: string;
  description?: string;
  buttons: ButtonComponent[];
}
export interface BannerSlideComponent_Plain {
  image: Media;
  title?: string;
  description?: string;
  buttons: ButtonComponent_Plain[];
}

export interface BannerSlideComponent_NoRelations {
  image: number;
  title?: string;
  description?: string;
  buttons: ButtonComponent_NoRelations[];
}

